### ISSUE TITLE
Everything above 4.0.2 breaks Cheongsam kind of Dress

### ISSUE THREAD

**Issue by BestRestUp3300** [Animal42069/BetterPenetration#11]
On 4.0.2 it Works, above that it has a weird issue pictures provided:

![HoneySelect2_iEN3I4oRu2](https://user-images.githubusercontent.com/65274305/130882617-549aa643-8b41-47f0-b4d6-e49573767490.png)
![HoneySelect2_mNhhQsLEnt](https://user-images.githubusercontent.com/65274305/130882620-bb9b61a8-806c-4b6a-aef6-724e8b94caa0.png)

Here is the card to test it with:

https://i.ibb.co/S5h1Xdj/HS2-Cha-F-20200603015224202.png

**Comment by pr0dukt** [comment]
Anything above 4.0.2 also creates a bunch of dick bone alignment issues with several of the kplug positions that don't utilize the BP bones and dick navigation during penetration. obviously don't expect kplug support for any mod outside of kplug itself, but figured I might as well make it known all the same. i've just been staying on 4.0.2 for the time being.

**Comment by Animal42069** [comment]
This is the same issue as: https://github.com/Animal42069/BetterPenetration/issues/13
This should be fixed in the 4.5.0 release
