### ISSUE TITLE
My findings about "Ghost Dick" deforming skirt issue

### ISSUE THREAD

**Issue by RepairUnit3k6** [Animal42069/BetterPenetration#13]
I did variety of experiments to gather more information on issue by trail and error. Related to #11 however I wanted start new issue so I wont clutter up #11. I hope my findings will aid in fixing the issue. Experiments were committed with HFPatch v3.12 and all mods updated using KKM

My finding are as follow :

- Issue is present in 4.4, sadly
- Caused by penis zipmods. No plugin .dll nor female or balls zipmods. As long as you have penis zipmod loaded, any of them issue will present itself
- You don't even need to have BP uncensor selected, ghost dick will appear regardless of body type as long as you have single penis zipmod installed
- You can use BP without issue occurring as long as you remove penis zipmods
- After you load character issue wont show nor after switching uncensor. Switching bottom clothing breaks it somehow
- Ghost dick is not affecting only skirts or clothing, but everything controlled by dynamic bones

**Comment by RepairUnit3k6** [comment]
> Thanks, this matches what I see as well. Sadly this is not a bug with BP or the zipmods per say, but an issue with uncensor selector. It is loading colliders onto the body even when the uncensor isn't loaded. If you remove everything from BP, including the plugin, but keep just 1 penis uncensor then the bug occurs. Even if the zipmod were buggy, it shouldn't have an impact on the game unless it is being loaded. In the past I was adding colliders during runtime, recently I started included them in the zipmod asset so that they could be sized to the model instead of using a generic size. This change exposed the uncensor selector bug. I don't have any control over what uncensor selector does... I had added some code to the BP plugin to remove these colliders when they incorrectly get loaded, which is why it doesn't show when you load a character/switch uncensor. I'll have to see if I can remove them when bottoms switch as well... its a shitty work around but it's the only thing I can do.

Perhaps it would be possible bug uncensor author into fixing it when it is bug in uncensor selector and not in BP ? I dont know who made it honestly, I cant find repo nowhere

**Comment by IDontHaveIdea** [comment]
Uncensor selector repo part of KK_Plugins:

https://github.com/IllusionMods/KK_Plugins

**Comment by IDontHaveIdea** [comment]
Hi,

If you set the scale of the Penis to 0 in Genitals effectively set the colliders to 0.  The problem won't show anymore.

**Comment by Animal42069** [comment]
> Hi,
> 
> If you set the scale of the Penis to 0 in Genitals effectively set the colliders to 0. The problem won't show anymore.

That's a really useful workaround, thanks!

**Comment by Animal42069** [comment]
I have added more checks to the BP plugin to remove the colliders when uncensor selector incorrectly adds them.  My biggest issues is that I wasn't patching until an HScene started, so when in studio the hooks were just never patched yet.  This will be part of the 4.5.0 release
