### ISSUE TITLE
BP pussy clipping with panties/pantyhose issue

### ISSUE THREAD

**Issue by HwuSam** [Animal42069/BetterPenetration#19]
As title said.

BP pussy mod had clipping issue with panties/pantyhose in specific animation.

![image](https://user-images.githubusercontent.com/72545569/149932289-1a4f5fec-2cb9-4a56-aad9-9d5e53a6a5c3.png)
![image](https://user-images.githubusercontent.com/72545569/149939817-45e29c41-539b-4cdf-b048-766bdde09b28.png)

**Comment by Animal42069** [comment]
This is unfortunately the way it is.  Clothing items have been skinned to the default body, which doesn't have the BP bones.  So when these bones move the body to open things up, it doesn't also move the clothing.  To fix would require remaking every piece of clothing with these bones.
