### ISSUE TITLE
Dynamic bone colliders in VR mode

### ISSUE THREAD

**Issue by cc19860910** [Animal42069/BetterPenetration#3]
hi there，the “Dynamic bone colliders” dosen’t work in VR mode.Dose it supported?

**Comment by Animal42069** [comment]
I don't have a VR system so can't really debug issues with it... best I can do is just enable it and hope it works

**Comment by dorianmeric** [comment]
hey both, I've created a fix for HoneySelect2VR (which was not loading/patching the HS2_BetterPenetration plugin during scenes when in VR).  I tested it with my Oculus Rift S and it works after making the change.

https://github.com/Animal42069/BetterPenetration/pull/6

**Comment by Animal42069** [comment]
Thanks dorian, your changes look good.  Only issue I have is deletions to the readme
